### ISSUE TITLE
Sub-par validations

### ISSUE THREAD

**Issue by fedenusy** [awslabs/aws-sdk-ruby-record#14] opened 2016-04-18 23:23 UTC
Hey guys, first off, thank you for making this gem! I love the fact that your architecture is true to DynamoDB, instead of forcing a fit with the ActiveRecord API.

I've started using `aws-record` in a new project and so far so good. The one thing that I'm unhappy with are validators.

Validators must define the `validate(value)` method. This is ok for very simple use cases, like validating the presence of a value, ensuring the value falls within a certain range, etc.

Unfortunately, this structure makes it impossible to handle more complex validation scenarios. For example, let's say I have a record with two fields: `ingredient` and `quantity`. If I want to validate that `quantity` falls within a specified range for a given `ingredient`, I have no way of doing this.

IMO you guys should either:

1. Not support validations and leave those up to the user.
2. Pass the record itself as an argument to the `validate` method. This seems like more of a hack than a proper solution, since now it no longer makes sense to define "validators" at the field level.
3. Take inspiration from ActiveRecord validators, and define validations at the record level.

**Comment by awood45** [comment] 2016-04-18 23:26
I'm actually leaning towards option 1 at this point. Validations as-is are a sort of vestige of an approach I'm going back and forth on, and bringing your own is reasonable for most cases.

Open to ideas on if leaving validations entirely out of this (or private-only, such as for key validation) is going to be problematic for anyone watching the repo.

**Comment by fedenusy** [comment] 2016-04-18 23:44
Private-only makes sense to me.

People can just `include ActiveModel::Validations` as needed.

**Comment by awood45** [comment] 2016-04-18 23:52
That bit about including ActiveModel::Validations is pretty much the intent. Leaving this open until I pull validations out, as I agree the inclusion is confusing.

**Comment by fedenusy** [comment] 2016-04-20 00:48
I just noticed 1.0.0.pre.5 defines `errors` and `valid?`, both of which clash with `ActiveModel::Validations`.

@awood45 does this mean the plan changed, and you're now leaning towards option 3?

**Comment by awood45** [comment] 2016-04-20 01:19
Might have been an oversight on my part, will look more in to that.

**Comment by awood45** [comment] 2016-04-20 01:21
Reading the docs, I'll do some testing with `ActiveModel::Validations` to get the story straight for that before GA. Clashing is not the intention.

**Comment by fedenusy** [comment] 2016-04-20 01:24
Sounds good, thanks for clarifying.

**Comment by fedenusy** [comment] 2016-04-20 01:48
@awood45 after taking a closer look, I'm noticing thread-unsafe code. From `item_operations.rb`:

```
# @api private
def self.included(sub_class)
  sub_class.extend(ItemOperationsClassMethods)
  sub_class.instance_variable_set("@errors", [])
end

...

def errors
  self.class.instance_variable_get("@errors")
end

...

def save(opts = {})
  result = save!(opts)
  errors.clear
  result
rescue Errors::RecordError => e
  errors << e.message
  false
end
```

The issue is the `@errors` class instance variable. If you were to `save` 2+ records concurrently, the `errors` array would be totally unreliable.

Hopefully this pattern isn't used anywhere else in the gem.

**Comment by fedenusy** [comment] 2016-04-20 02:09
And for the (aws-)record, thread safety is a requirement across all my projects. 

You'll also find a large number of Ruby users who care about thread safety, even if they don't use concurrency patterns directly.

For example, the popular sidekiq gem for background workers relies on a thread pool executor. It's practically impossible to use sidekiq with thread-unsafe gems.

**Comment by awood45** [comment] 2016-04-20 02:13
That would be a bug/oversight in my PR review. It should be item instance level.

**Comment by awood45** [comment] 2016-04-20 02:15
As for other class-level variables, those would be reserved for model attributes, which shouldn't really be modified often (it takes a migration to do so in some cases).

If you see other such cases, feel free to open an issue.

**Comment by fedenusy** [comment] 2016-04-20 03:55
Ok, good to hear. I was worried that the gem wasn't built with
thread-safety in mind. Unfortunately I've gotten bit by this kinda bug many
times :(

Before pushing to production I'll do some thread-safety testing on sidekiq.
Will open issues if anything comes up.

**Comment by awood45** [comment] 2016-04-20 03:59
I'm going to move that discussion to a new issue, since this was intended for another one.

**Comment by awood45** [comment] 2016-04-20 22:08
I've resolved the concurrency issue, but I wouldn't use these methods. I'll be deprecating them and releasing a new validations strategy.

**Comment by awood45** [comment] 2016-04-20 22:08
That new validations strategy should resolve this issue as well.

**Comment by awood45** [comment] 2016-04-21 21:34
Resolving this, I believe that these concerns should be addressed (and regression tested) going forward.

**Closed** 2016-04-21 21:34 UTC
Labels: enhancement
